[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_STACK_PROJECT_ID = "4ed40039-6db7-498b-a4ff-844327ee0229"
  VITE_STACK_PUBLISHABLE_CLIENT_KEY = "pck_2rzy4m97drzcptv5zzsef6dfa1rvtccqxjpn8xgyt99er"
  STACK_SECRET_SERVER_KEY = "ssk_3tk7eekem9hmnddswsbtvfkw3z5p7t2q589qrrdggftbg"
  DATABASE_URL = "postgresql://neondb_owner:npg_8WdTlBKStax0@ep-frosty-sun-a1pdxel5-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
  NEON_REST_API_URL = "https://ep-frosty-sun-a1pdxel5.apirest.ap-southeast-1.aws.neon.tech/neondb/rest/v1"
  JWKS_URL = "https://api.stack-auth.com/api/v1/projects/4ed40039-6db7-498b-a4ff-844327ee0229/.well-known/jwks.json"

# API redirects to serverless functions (must come before SPA fallback)
[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders-simple"
  status = 200

[[redirects]]
  from = "/api/customers"
  to = "/.netlify/functions/customers-simple"
  status = 200

[[redirects]]
  from = "/api/dashboard/metrics"
  to = "/.netlify/functions/dashboard-metrics-simple"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/orders-simple"
  status = 200

[[redirects]]
  from = "/api/services"
  to = "/.netlify/functions/orders-simple"
  status = 200

[[redirects]]
  from = "/api/deliveries"
  to = "/.netlify/functions/orders-simple"
  status = 200

[[redirects]]
  from = "/api/health/database"
  to = "/.netlify/functions/dashboard-metrics-simple"
  status = 200

[[redirects]]
  from = "/api/database/info"
  to = "/.netlify/functions/dashboard-metrics-simple"
  status = 200

# SPA fallback for client-side routing - MUST be last
# This rule catches all unmatched routes and serves index.html
# allowing React Router to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"