[build]
  # Build command
  command = "npm run build"
  
  # Publish directory - this is where the built files are located
  publish = "dist/public"
  
  # Functions directory (if you have any Netlify functions)
  # functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for Netlify Identity
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["*"]}

# Allow access to login page for everyone
[[redirects]]
  from = "/login.html"
  to = "/login.html"
  status = 200

# Allow access to Netlify Identity callback
[[redirects]]
  from = "/.netlify/identity"
  to = "/.netlify/identity"
  status = 200

# Allow access to static assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
