BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.customers
  ADD COLUMN IF NOT EXISTS wallet_balance_cache numeric(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS credit_balance numeric(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS credit_limit numeric(10, 2);

ALTER TABLE public.wallet_transactions
  ADD COLUMN IF NOT EXISTS entry_no bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS franchise_id text,
  ADD COLUMN IF NOT EXISTS transaction_type text,
  ADD COLUMN IF NOT EXISTS payment_method text,
  ADD COLUMN IF NOT EXISTS reference_type text,
  ADD COLUMN IF NOT EXISTS reference_id text,
  ADD COLUMN IF NOT EXISTS note text,
  ADD COLUMN IF NOT EXISTS created_by text;

UPDATE public.wallet_transactions
SET
  transaction_type = CASE
    WHEN transaction_type IS NOT NULL THEN transaction_type
    WHEN lower(coalesce(type, '')) = 'credit' THEN 'CREDIT'
    WHEN lower(coalesce(type, '')) = 'debit' THEN 'DEBIT'
    WHEN coalesce(amount, 0) >= 0 THEN 'CREDIT'
    ELSE 'DEBIT'
  END,
  payment_method = coalesce(payment_method, 'CASH'),
  reference_type = CASE
    WHEN reference_type IS NOT NULL THEN reference_type
    WHEN reference_order_id IS NOT NULL AND lower(coalesce(type, '')) = 'debit' THEN 'ORDER'
    WHEN reference_order_id IS NOT NULL THEN 'PAYMENT'
    ELSE 'MANUAL'
  END,
  reference_id = coalesce(reference_id, reference_order_id),
  note = coalesce(note, transaction_id),
  created_by = coalesce(created_by, verified_by_staff)
WHERE transaction_type IS NULL
   OR payment_method IS NULL
   OR reference_type IS NULL
   OR reference_id IS NULL
   OR note IS NULL
   OR created_by IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_wallet_transactions_entry_no_unique
  ON public.wallet_transactions(entry_no);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_customer_entry
  ON public.wallet_transactions(customer_id, entry_no DESC);

CREATE INDEX IF NOT EXISTS idx_wallet_transactions_reference
  ON public.wallet_transactions(reference_type, reference_id)
  WHERE reference_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.wallet_transactions_before_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_previous_balance numeric(10, 2);
BEGIN
  IF new.customer_id IS NULL OR btrim(new.customer_id) = '' THEN
    RAISE EXCEPTION 'customer_id is required';
  END IF;

  SELECT wt.balance_after
  INTO v_previous_balance
  FROM public.wallet_transactions wt
  WHERE wt.customer_id = new.customer_id
  ORDER BY wt.entry_no DESC NULLS LAST, wt.created_at DESC, wt.id DESC
  LIMIT 1;

  v_previous_balance := coalesce(v_previous_balance, 0);

  IF new.transaction_id IS NULL OR btrim(new.transaction_id) = '' THEN
    new.transaction_id := 'TXN-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS') || '-' || substring(md5(random()::text), 1, 6);
  END IF;

  new.transaction_type := upper(coalesce(new.transaction_type, CASE WHEN coalesce(new.amount, 0) >= 0 THEN 'CREDIT' ELSE 'DEBIT' END));
  IF new.transaction_type NOT IN ('CREDIT', 'DEBIT', 'ADJUSTMENT') THEN
    RAISE EXCEPTION 'Unsupported transaction_type: %', new.transaction_type;
  END IF;

  new.reference_type := upper(coalesce(new.reference_type, 'MANUAL'));
  IF new.reference_type NOT IN ('PAYMENT', 'ORDER', 'ADJUSTMENT', 'MANUAL') THEN
    RAISE EXCEPTION 'Unsupported reference_type: %', new.reference_type;
  END IF;

  new.payment_method := CASE
    WHEN new.payment_method IS NULL OR btrim(new.payment_method) = '' THEN NULL
    ELSE upper(replace(new.payment_method, ' ', '_'))
  END;

  IF new.payment_method IS NOT NULL
     AND new.payment_method NOT IN ('CASH', 'UPI', 'BANK_TRANSFER', 'CARD', 'CHEQUE', 'NET_BANKING', 'OTHER') THEN
    new.payment_method := 'OTHER';
  END IF;

  IF new.amount IS NULL OR new.amount = 0 THEN
    RAISE EXCEPTION 'amount must be non-zero';
  END IF;

  new.balance_before := coalesce(new.balance_before, v_previous_balance);
  new.balance_after := coalesce(new.balance_after, v_previous_balance + new.amount);
  new.type := coalesce(new.type, lower(CASE WHEN new.transaction_type = 'DEBIT' THEN 'debit' ELSE 'credit' END));
  new.reference_order_id := coalesce(new.reference_order_id, CASE WHEN new.reference_type = 'ORDER' THEN new.reference_id END);
  new.created_at := coalesce(new.created_at, now());

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trg_wallet_transactions_before_insert ON public.wallet_transactions;
CREATE TRIGGER trg_wallet_transactions_before_insert
BEFORE INSERT ON public.wallet_transactions
FOR EACH ROW EXECUTE FUNCTION public.wallet_transactions_before_insert();

CREATE OR REPLACE FUNCTION public.wallet_transactions_after_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM set_config('app.wallet_sync', 'on', true);

  UPDATE public.customers c
  SET wallet_balance_cache = new.balance_after,
      credit_balance = CASE WHEN new.balance_after < 0 THEN abs(new.balance_after) ELSE 0 END,
      updated_at = now()
  WHERE c.id = new.customer_id;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trg_wallet_transactions_after_insert ON public.wallet_transactions;
CREATE TRIGGER trg_wallet_transactions_after_insert
AFTER INSERT ON public.wallet_transactions
FOR EACH ROW EXECUTE FUNCTION public.wallet_transactions_after_insert();

CREATE OR REPLACE FUNCTION public.prevent_wallet_transaction_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'wallet_transactions is immutable. Use new ledger entries instead.';
END;
$$;

DROP TRIGGER IF EXISTS trg_wallet_transactions_block_mutation ON public.wallet_transactions;
CREATE TRIGGER trg_wallet_transactions_block_mutation
BEFORE UPDATE OR DELETE ON public.wallet_transactions
FOR EACH ROW EXECUTE FUNCTION public.prevent_wallet_transaction_mutation();

CREATE OR REPLACE FUNCTION public.prevent_manual_wallet_customer_updates()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (new.wallet_balance_cache IS DISTINCT FROM old.wallet_balance_cache
      OR new.credit_balance IS DISTINCT FROM old.credit_balance)
     AND coalesce(current_setting('app.wallet_sync', true), 'off') <> 'on' THEN
    RAISE EXCEPTION 'Wallet/credit balances are ledger-derived and cannot be updated directly';
  END IF;

  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trg_customers_block_manual_wallet_update ON public.customers;
CREATE TRIGGER trg_customers_block_manual_wallet_update
BEFORE UPDATE ON public.customers
FOR EACH ROW EXECUTE FUNCTION public.prevent_manual_wallet_customer_updates();

WITH latest_balances AS (
  SELECT DISTINCT ON (wt.customer_id)
    wt.customer_id,
    wt.balance_after
  FROM public.wallet_transactions wt
  ORDER BY wt.customer_id, wt.entry_no DESC NULLS LAST, wt.created_at DESC, wt.id DESC
)
UPDATE public.customers c
SET wallet_balance_cache = coalesce(lb.balance_after, 0),
    credit_balance = CASE WHEN coalesce(lb.balance_after, 0) < 0 THEN abs(lb.balance_after) ELSE 0 END,
    updated_at = now()
FROM latest_balances lb
WHERE c.id = lb.customer_id;

UPDATE public.customers
SET wallet_balance_cache = coalesce(wallet_balance_cache, 0),
    credit_balance = coalesce(credit_balance, 0)
WHERE wallet_balance_cache IS NULL
   OR credit_balance IS NULL;

COMMIT;
